SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 0
TRAIN:
  DA_METHOD: MinEnt
  MODEL: DeepLabv2
  RESTORE_FROM: E:/ADVENT-master/advent/pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: True
  LAMBDA_ENT_MAIN: 0.001
  LAMBDA_ENT_AUX: 0.0002
TEST:
  MODE: best